glyph/automat

automat/_methodical.py
automat/_test/test_methodical.py

`automat._core.Automaton.outputForInput` implies that an invalid transition
should raise a `NotImplementedError`.  In practice, though,
`MethodicalMachine` may raise a `KeyError` because there's no
collector specified for a given state, because no transitions exist.
Reorder the code to always raise a `NotImplementedError`, add a test
to ensure this, and change the repr methods of various machine
components to succinctly describe themselves.

   Invalid transitions should raise NotImplementedError.

---

tox.ini

I noticed that Travis doesn't run any tests for Python 3.2, but tox does.  So I removed `py32` from tox's env list.

remove py32 from tox.ini, keeping it in line with .travis.yml

---

automat/_core.py
automat/_methodical.py
automat/_test/test_core.py
automat/_test/test_methodical.py
automat/_visualize.py

These were in `test_core`:
- test `addTransition` with outputs that aren't iterable
- add a public API for an `Automaton`'s initial state.  Note that a DFA can only have one initial state, so there's no longer a set of initial states, and you can only set the initial state once.

Fix some FIXMEs

---

automat/__init__.py
automat/_core.py
automat/_test/test_core.py
automat/_test/test_methodical.py

NotImplementedError.
see discussion in #15.
@moshez - does this seem ok?  note that it doesn't inherit from `ValueError`.
@glyph - while writing this it occurred to me that `NoTransition` might be a better name than `InvalidStateForInput`.  what do you think?  also, i've never written epytext so look out for weirdness in the docstrings!

Invalid transitions now raise NoTransition instead of

---

.travis.yml
tox.ini

Previously, each environment's coverage data overwrote any other's, so
that checking the coverage locally showed only the last run's results.
This approach was largely cribbed from
https://hynek.me/articles/testing-packaging/

tox.ini now combines the coverage data from all test environments.

---

automat/__main__.py
automat/_discover.py
automat/_methodical.py
automat/_test/test_discover.py
automat/_test/test_visualize.py
automat/_visualize.py
setup.py
tox.ini

Closes #5.
This PR builds on #20 so it appears slightly weightier than it is.  Make no mistake -- this is a very large PR, but I don't know if it could be made smaller.
There are again two commits:
1) Introduces the discovery logic used by the visualization tool.  This is largely cribbed from t.p.modules, and indeed the hardest part -- module exploration -- is handled by `PythonModule`.  Unfortunately there is no version of `namedAny` that returns `PythonModule` or `PythonAttributes` instead of actual objects.  This meant either using less of t.p.modules (which appears to be what `trial` does) or reimplementing `namedAny` in terms of t.p.modules objects.  I chose the latter.  An open question here: should `findMachinesViaWrapper` (and thus `findMachines`) accept an argument to ignore …

Visualizer tool

---

automat/_test/test_methodical.py
automat/_visualize.py
setup.py

The argument parser uses it to fail early when given an unsupported
image format.  Since the graphviz library itself determines what image
formats it supports, the contents of the set isn't private, but its
location inside the graphviz Python package is.
This commit copies the set into _visualize to break the dependency on
this private API.

Stop using graphviz's private FORMATS set.

---

automat/__main__.py

The automat-visualize console script is the only public API to the
visualizer for now.
(See https://github.com/glyph/automat/pull/32#issuecomment-266242546)

Remove automat.__main__.

---

automat/_methodical.py
automat/_test/test_visualize.py
setup.py

characteristic -> automat; remove attrs name conflict in tests

---

automat/_methodical.py

I encountered a lot of these deprecation warnings when running the buildbot unit tests,
while porting buildbot to Py3.

Use inspect.getfullargspec on Py3 to avoid deprecation warnings with inspect.getargspec

---

setup.py

Update the `setup` keyword args for author contact to align with the
[`distutils.core` API](https://docs.python.org/3.6/distutils/apiref.html).

Conform author metadata to `distutils.core` API

---

.travis.yml
tox.ini

just py3.5 this time
Travis doesn't include py3.6 on their default `language: python` image, so we'll need something extra to enable py3.6 support.

tox/travis: enable tests on py3.5

---

automat/_methodical.py
automat/_test/test_methodical.py

This should be more future-proof, as it compares the target Input's bytecode
against one of two samples (which will be compiled by the same interpreter as
the target), rather than comparing it against magic integers.
This passes manual local tests (with a modified tox.ini that adds a py3.6 target).

improve function-is-empty test to work on py3.6 too

---

.travis.yml
tox.ini

~Now that travis supports py3.6 directly, this is a lot easier.~
Edit: travis hasn't changed. I had to rewrite the .travis.yml to create separate environments for each target version.

tox/travis: enable tests on py3.6

---

automat/_core.py
automat/_methodical.py
automat/_test/test_trace.py
docs/debugging.md

refs #36 
This seems useful for my own debugging purposes, where the logging function is just `print()`.
Some questions still in my mind:
* Is the tracing function sufficient to collect transition-coverage information, for #37/#38?
* This replaces the generator of outputs with a list, which probably inadvertently fixes #30
* The use of output=None vs output=(string) doesn't really capture the causality of transitions and their output functions being invoked. A properly structured logging framework (like Eliot or Foolscap) would be unsatisfied. Some other approaches would be:
* register two separate logging functions (one for transitions, another for outputs), and have the return value from the first get passed as an extra argument into the second
* pass an additional argument with some …

add tracing API, with docs

---

automat/_methodical.py

This version of attrs no longer makes classes hashable by default.
Instead, hashability must be explicitly requested or the class must be
made frozen.
MethodicalInput and MethodicalOutput are both added to a set inside
_core.Automaton, so they both have to be hashable.  Neither are ever
modified, however, so they can be made frozen and thus hashable.

Make hashable classes frozen for attrs 17.1.0 (fixes #62).

---

docs/about.rst

One method in this example was partially mis-indented.

Correct CoffeeBrewer state example indentation

---

automat/_methodical.py
automat/_test/test_methodical.py

There are some artificial restrictions that this implementation imposes
for the sake of simplicity.
- outputs may accept *args if and only if the input accepts *args
- outputs may accept **kwargs if and only if the input accepts **kwargs
- If a py3 type annotation is present on an argument in an output's signature
then the same argument and type annotation must appear
in the input's signature.

accept outputs with fewer arguments than their inputs per issue #29

---

.travis.yml

twisted requires python 3.4+
In relation to PR #95 TravisCI error

remove python 3.3 from test environments

---

README.md

I added two links to the great presentations of Automat made last year. I find it useful to have these readily available in the readme, and others may too.  
Please let me know if you think the added screenshots are obtrusive, or if you'd rather see the links located at the bottom of the page instead.
Cheers,
Fred

add links to presentation videos

---

.travis.yml
automat/_core.py
automat/_test/test_core.py
setup.py
tox.ini

Python 3.3 was commented out from the CI in #98.
As Python 3.3 is EOL and no longer receiving security updates (or any updates) from the core Python team, let's remove it instead of commenting out.
Also remove 3.3 from:
* https://github.com/glyph/automat/blob/master/setup.py#L55
* https://github.com/glyph/automat/blob/master/tox.ini#L2
This also upgrades Python syntax with https://github.com/asottile/pyupgrade.
---
Pip installs for automat from PyPI for May 2018:
| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  57.26% |        100,491 |
| 3.6            |  24.31% |         42,663 |
| 3.5            |  16.10% |         28,255 |
| 3.4            |   1.93% |          3,385 |
| 3.7            |   0.40% |            697 |
| 2.6 …

Drop support for EOL Python 3.3

---

tox.ini

This fixes the failing build on master.

constrain twisted dep for python 3.4

---

.travis.yml
automat/_introspection.py
setup.py

PEP 570 adds "positional only" arguments to Python, which changes the
code object constructor. This adds support for Python 3.8.
Signed-off-by: Robert-André Mauchin <zebob.m@gmail.com>
(update of #111)

Add support for positional only arguments

---

README.md

GitHub embeds links to youtube as videos, resulting in odd-looking `README.md` (on OSX/Safari). So it's nicer this way :)

Added double-spaces after embedded youtube links

---

automat/_test/test_visualize.py

When graphviz modules are installed but not twisted, this creates test failures
due to _visualize.py importing _discover.py which hard depends on twisted being installed.
Signed-off-by: Brian Dolbec <dolsen@gentoo.org>

Fix _test_visualize.py twisted import errors

---

docs/about.rst

Instead of `next()`, use `operator.itemgetter(0)`
I haven't done any of the other things suggested
(adding `first()` to the library itself or adding auto-testing for the docs).

Fix #129: Fix docs to remove invalid next

---

automat/_methodical.py
automat/_test/test_methodical.py

Since enter follows outputs, and there are some use cases
(including in the tests) which use the argument order,
this also allows outputs to have a default. This has been
discussed before (in the same ticket) as desirable.

Fix #17: Allow enter to have a default

---

automat/_introspection.py

Use CodeType.replace() in copycode for Python > 3.8
